export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';


export const GET_COWORKINGSPACE = 'GET_COWORKINGSPACE';
export const COWORKINGSPACE_LOADING = 'COWORKINGSPACE_LOADING';
export const COWORKINGSPACE_NOT_FOUND = 'COWORKINGSPACE_NOT_FOUND';
export const CLEAR_CURRENT_COWORKINGSPACE = 'CLEAR_CURRENT_COWORKINGSPACE';
export const GET_COWORKINGSPACES = 'GET_COWORKINGSPACES';


export const GET_STORES = 'GET_STORES';
export const STORES_LOADING = 'STORES_LOADING';
export const STORES_NOT_FOUND = 'STORES_NOT_FOUND';
export const CLEAR_CURRENT_STORES = 'CLEAR_CURRENT_STORES';

export const GET_MATERIAL = 'GET_MATERIAL';
export const GET_MATERIALS = 'GET_MATERIALS';
export const MATERIALS_LOADING = 'MATERIALS_LOADING';
export const MATERIALS_NOT_FOUND = 'MATERIALS_NOT_FOUND';
export const CLEAR_CURRENT_MATERIALS = 'CLEAR_CURRENT_MATERIALS';

export const GET_RESOURCES = 'GET_RESOURCES';
export const GET_RESOURCE = 'GET_RESOURCE';
export const RESOURCES_LOADING = 'RESOURCES_LOADING';
export const RESOURCES_NOT_FOUND = 'RESOURCES_NOT_FOUND';
export const CLEAR_CURRENT_RESOURCES = 'CLEAR_CURRENT_RESOURCES';

export const GET_OWNERS = 'GET_OWNERS';
export const GET_OWNER = 'GET_OWNER';
export const OWNERS_LOADING = 'OWNERS_LOADING';
export const OWNERS_NOT_FOUND = 'OWNERS_NOT_FOUND';
export const CLEAR_CURRENT_OWNERS = 'CLEAR_CURRENT_OWNERS';


