export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';


export const GET_COWORKINGSPACE = 'GET_COWORKINGSPACE';
export const COWORKINGSPACE_LOADING = 'COWORKINGSPACE_LOADING';
export const COWORKINGSPACE_NOT_FOUND = 'COWORKINGSPACE_NOT_FOUND';
export const CLEAR_CURRENT_COWORKINGSPACE = 'CLEAR_CURRENT_COWORKINGSPACE';
export const GET_COWORKINGSPACES = 'GET_COWORKINGSPACES';
